### ISSUE TITLE
Add Hospitalisierungsinzidenz and Belegte Intensivbetten in Hessen as data and/or graph

### ISSUE THREAD

**Issue by JSoko** [DSoko2/Corona-NI#16]
![grafik](https://user-images.githubusercontent.com/5583290/134120102-dcaa24cf-63fc-4cbb-b51f-ab9069f244bf.png)
https://www.kreis-offenbach.de/Themen/Gesundheit-Verbraucher-schutz/akut/Corona/Corona-Entwicklung/Tagesmeldung-vom-20-September-2021-Wochenend-%C3%9Cbersicht-.php?object=tx,2896.3&ModID=6&FID=2896.6187.1&NavID=2896.1158&La=1

**Comment by DSoko2** [comment]
Done and available at https://corona.dsoko.de/hessen
